spring.application.name=demo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bsautomacao.fechamentos@gmail.com
spring.mail.password=czpj qntc bpqk sadk
spring.mail.properties.mail.smtp.auth=true
